### ISSUE TITLE
Install without composer?

### ISSUE THREAD

**Issue by Bdoom** [EloGank/lol-replay-downloader#4]
Is there a way to install this without composer? I just want to be able to use plain PHP because I don't have root access on my server.

**Comment by Divi** [comment]
Unfortunately no. But you can install the `composer.phar` file into the project directory, which doesn't require `sudo` privilege.

``` bash
cd your_project_directory
wget https://getcomposer.org/composer.phar
php composer.phar install
```

**Comment by Bdoom** [comment]
So once I have that file I can just go to it in a web browser? Then what?

**Comment by Divi** [comment]
No, not in browser but with your CLI.
Just run these commands on your project directory, it will download all dependencies :

``` bash
cd your_project_directory
wget https://getcomposer.org/composer.phar
php composer.phar install
```

Then you can use the Replay Downloader. See an example here : https://github.com/EloGank/lol-replay-downloader/blob/master/examples/download-replay.php

**Comment by Bdoom** [comment]
hm
